name = "deadtime-server"
main = "worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "../public"
binding = "ASSETS"
not_found_handling = "404-page"

[[kv_namespaces]]
binding = "INSTALLS"
id = "89e54ed8387646c8bc59fb73fab91bea"

[[kv_namespaces]]
binding = "LEADS"
id = "ce046c03849944d6808b0e3f2030186d"

[[kv_namespaces]]
binding = "CAMPAIGNS"
id = "828f436d4e784be0b762b54a922c8243"

[[kv_namespaces]]
binding = "ERRORS"
id = "83a97e184c3d485ca30e075b48aee2fb"

[ai]
binding = "AI"

[triggers]
crons = ["11 6 * * *", "*/20 * * * *"]
